subscribedproducttmfwebservices.v3.api.restrictions.disabled.endpoints= 
agreementtmfwebservices.v3.api.restrictions.disabled.endpoints=
billmanagementtmfwebservices.api.restrictions.disabled.endpoints=
billingaccounttmfwebservices.api.restrictions.disabled.endpoints=
b2ctelcotmfwebservices.api.restrictions.disabled.endpoints=
productqualificationservices.product.characteristic.feature.disabled=false
productqualificationservices.product.price.feature.disabled=false
flexible.search.exception.show.query.details=true
solrfacetsearch.fullSpELSupport=true
impex.import.workers=1
storefrontContextRoot=telcospa
catalog.sync.workers=1
kernel.events.cluster.jgroups.channel=disable
datahub.publication.saveImpex=
kernel.autoInitMode=update
mail.from=testmail9110@gmail.com
mail.replyto=testmail9110@gmail.com
mail.smtp.server=smtp.gmail.com
mail.smtp.port=587
mail.smtp.user=testmail9110@gmail.com
mail.smtp.password=PWD11111
mail.smtp.starttls.enable=true
mail.use.tls=true
storefront.show.debug.info=true
commerceservices.default.desktop.ui.experience=responsive
googleEmbedApiKey=AIzaSyD34TXbUsiyJnysJ-1Un657elxVy_OYpTs
storefront.show.checkout.flows=true
agreementtmfwebservices.api.base.url=${ccv2.services.api.url.0}
b2ctelcocommercewebservicescommons.api.base.url=${ccv2.services.api.url.0}
b2ctelcotmfevents.api.base.url=${ccv2.services.api.url.0}
b2ctelcotmfresources.api.base.url=${ccv2.services.api.url.0}
b2ctelcotmfwebservices.api.base.url=${ccv2.services.api.url.0}
billingaccounttmfwebservices.api.base.url=${ccv2.services.api.url.0}
billmanagementtmfwebservices.api.base.url=${ccv2.services.api.url.0}
partyroletmfwebservices.api.base.url=${ccv2.services.api.url.0}
partytmfwebservices.api.base.url=${ccv2.services.api.url.0}
subscribedproducttmfwebservices.api.base.url=${ccv2.services.api.url.0}
usageconsumptiontmfwebservices.api.base.url=${ccv2.services.api.url.0}
productqualificationtmfwebservices.api.base.url=${ccv2.services.api.url.0}
b2ctelcomocks.api.base.url=${ccv2.services.api.url.0}
commercewebservices.oauth2.tokenUrl=${ccv2.services.api.url.0}/authorizationserver/oauth/token
commercewebservices.sap.server.default.url=${ccv2.services.api.url.0}/occ/v2
cmswebservices.oauth.host=${ccv2.services.api.url.0}
cmswebservices.oauth2.tokenUrl=${ccv2.services.api.url.0}/authorizationserver/oauth/token
ext.cmsocc.extension.webmodule.webroot=${ccv2.services.api.url.0}/occ/v2
cmswebservices.sap.server.default.url=${ccv2.services.api.url.0}/cmswebservices
session.default.baseSiteId=b2ctelcotesting
session.default.baseStoreId=b2ctelcotesting
sop.post.url=${ccv2.services.api.url.0}/acceleratorservices/sop-mock/process
system.unlocking.disabled=false
installed.tenants=
task.engine.loadonstartup=true
ruleengineservices.compiler.task.predestroytimeout=60000000
api.compatibility.b2c.channels=B2C
api.compatibility.b2b.channels=B2B
ycommercewebservices.oauth2.tokenUrl=${ccv2.services.api.url.0}/authorizationserver/oauth/token
ycommercewebservices.sap.server.default.url=${ccv2.services.api.url.0}/rest/v2
webservicescommons.apiEnv.oauth2.tokenUrl=${ccv2.services.api.url.0}/authorizationserver/oauth/token
corsfilter.default.allowedOrigins=*
corsfilter.acceleratorservices.allowedOrigins=*
corsfilter.permissionswebservices.allowedOrigins=*
corsfilter.commercewebservices.allowedOrigins=${ccv2.services.jsapps.url.0}
corsfilter.commercewebservices.allowedHeaders=origin content-type accept authorization cache-control if-none-match x-anonymous-consents
corsfilter.commercewebservices.allowedMethods=GET HEAD OPTIONS PATCH PUT POST DELETE
corsfilter.acceleratorservices.allowedOrigins=${ccv2.services.jsapps.url.0} ${ccv2.services.b2ctelco.url.0}
corsfilter.acceleratorservices.allowedHeaders=origin content-type accept authorization cache-control if-none-match x-anonymous-consents
corsfilter.acceleratorservices.allowedMethods=GET HEAD OPTIONS PATCH PUT POST DELETE
corsfilter.b2ctelcotmfwebservices.allowedOrigins=${ccv2.services.jsapps.url.0}
corsfilter.b2ctelcotmfwebservices.allowedHeaders=origin content-type accept authorization cache-control if-none-match x-anonymous-consents
corsfilter.b2ctelcotmfwebservices.allowedMethods=GET HEAD OPTIONS PATCH PUT POST DELETE
corsfilter.subscribedproducttmfwebservices.allowedOrigins=${ccv2.services.jsapps.url.0}
corsfilter.subscribedproducttmfwebservices.allowedHeaders=origin content-type accept authorization cache-control if-none-match x-anonymous-consents
corsfilter.subscribedproducttmfwebservices.allowedMethods=GET HEAD OPTIONS PATCH PUT POST DELETE
corsfilter.billingaccounttmfwebservices.allowedOrigins=${ccv2.services.jsapps.url.0}
corsfilter.billingaccounttmfwebservices.allowedHeaders=origin content-type accept authorization cache-control if-none-match x-anonymous-consents
corsfilter.billingaccounttmfwebservices.allowedMethods=GET HEAD OPTIONS PATCH PUT POST DELETE
corsfilter.agreementtmfwebservices.allowedOrigins=${ccv2.services.jsapps.url.0}
corsfilter.agreementtmfwebservices.allowedHeaders=origin content-type accept authorization cache-control if-none-match x-anonymous-consents
corsfilter.agreementtmfwebservices.allowedMethods=GET HEAD OPTIONS PATCH PUT POST DELETE
corsfilter.productqualificationtmfwebservices.allowedOrigins=${ccv2.services.jsapps.url.0}
corsfilter.productqualificationtmfwebservices.allowedHeaders=origin content-type accept authorization cache-control if-none-match x-anonymous-consents
corsfilter.productqualificationtmfwebservices.allowedMethods=GET HEAD OPTIONS PATCH PUT POST DELETE
corsfilter.billmanagementtmfwebservices.allowedOrigins=${ccv2.services.jsapps.url.0}
corsfilter.billmanagementtmfwebservices.allowedHeaders=origin content-type accept authorization cache-control if-none-match x-anonymous-consents
corsfilter.billmanagementtmfwebservices.allowedMethods=GET HEAD OPTIONS PATCH PUT POST DELETE
corsfilter.partytmfwebservices.allowedOrigins=${ccv2.services.jsapps.url.0}
corsfilter.partytmfwebservices.allowedHeaders=origin content-type accept authorization cache-control if-none-match x-anonymous-consents
corsfilter.partytmfwebservices.allowedMethods=GET HEAD OPTIONS PATCH PUT POST DELETE
corsfilter.partyroletmfwebservices.allowedOrigins=${ccv2.services.jsapps.url.0}
corsfilter.partyroletmfwebservices.allowedHeaders=origin content-type accept authorization cache-control if-none-match x-anonymous-consents
corsfilter.partyroletmfwebservices.allowedMethods=GET HEAD OPTIONS PATCH PUT POST DELETE
corsfilter.usageconsumptiontmfwebservices.allowedOrigins=${ccv2.services.jsapps.url.0}
corsfilter.usageconsumptiontmfwebservices.allowedHeaders=origin content-type accept authorization cache-control if-none-match x-anonymous-consents
corsfilter.usageconsumptiontmfwebservices.allowedMethods=GET HEAD OPTIONS PATCH PUT POST DELETE
corsfilter.b2ctelcomocks.allowedOrigins=*
corsfilter.b2ctelcomocks.allowedHeaders=origin content-type accept authorization cache-control if-none-match x-anonymous-consents
corsfilter.b2ctelcomocks.allowedMethods=GET HEAD OPTIONS PATCH PUT POST DELETE
website.utilitiesspa.https=${ccv2.services.jsapps.url.0}
website.utilitiesspa.http=${ccv2.services.jsapps.url.0}
website.telcospa.https=${ccv2.services.jsapps.url.0}
website.telcospa.http=${ccv2.services.jsapps.url.0}
website.mediaspa.https=${ccv2.services.jsapps.url.0}
website.mediaspa.http=${ccv2.services.jsapps.url.0}
occ.rewrite.overlapping.paths.enabled=true
b2ctelcotmfwebservices.api.basesiteId=/b2ctelcotesting
mockup.payment.label.billTo.region=billTo_state
mockup.payment.label.billTo.phoneNumber=billTo_phoneNumber
yacceleratorordermanagement.fraud.scoreLimit=500000
yacceleratorordermanagement.fraud.scoreTolerance=500000
yacceleratorordermanagement.fraud.scoreLimitExternal=500000
yacceleratorordermanagement.fraud.scoreToleranceExternal=500000
acceleratorservices.payment.sopmock.enabled=true
authserver.keystore.location=/opt/hybris/config/security/ccv2-authserver-keystore-file.jks
authserver.keystore.alias=oauth2key
authserver.keystore.password=t3sting
authserver.keystore.key.generate=false
authserver.key.password=t3sting
authserver.oauthclientdetails.loginpageuri.allowed.hosts=localhost
toggle.customerCorrelationWithMultipleParties.enabled=true
utilitiesspastore.s4.integration.feature.enabled=true
domain.auth.url=${env.DOMAIN_AUTH_URL}
domain.auth.clientId=${env.DOMAIN_AUTH_CLIENT_ID}
domain.auth.clientSecret=${env.DOMAIN_AUTH_CLIENT_SECRET}
search.service.url=${env.SEARCH_SERVICE_URL}
